/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TiendaRouteImport } from './routes/tienda'
import { Route as SeguimientoRouteImport } from './routes/seguimiento'
import { Route as PanelRouteImport } from './routes/panel'
import { Route as MayoristaRouteImport } from './routes/mayorista'
import { Route as IngresarRouteImport } from './routes/ingresar'
import { Route as CarritoRouteImport } from './routes/carrito'
import { Route as CajaRouteImport } from './routes/caja'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductoIdRouteImport } from './routes/producto.$id'
import { Route as PedidoIdRouteImport } from './routes/pedido.$id'

const TiendaRoute = TiendaRouteImport.update({
  id: '/tienda',
  path: '/tienda',
  getParentRoute: () => rootRouteImport,
} as any)
const SeguimientoRoute = SeguimientoRouteImport.update({
  id: '/seguimiento',
  path: '/seguimiento',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRoute = PanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const MayoristaRoute = MayoristaRouteImport.update({
  id: '/mayorista',
  path: '/mayorista',
  getParentRoute: () => rootRouteImport,
} as any)
const IngresarRoute = IngresarRouteImport.update({
  id: '/ingresar',
  path: '/ingresar',
  getParentRoute: () => rootRouteImport,
} as any)
const CarritoRoute = CarritoRouteImport.update({
  id: '/carrito',
  path: '/carrito',
  getParentRoute: () => rootRouteImport,
} as any)
const CajaRoute = CajaRouteImport.update({
  id: '/caja',
  path: '/caja',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductoIdRoute = ProductoIdRouteImport.update({
  id: '/producto/$id',
  path: '/producto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoIdRoute = PedidoIdRouteImport.update({
  id: '/pedido/$id',
  path: '/pedido/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/caja': typeof CajaRoute
  '/carrito': typeof CarritoRoute
  '/ingresar': typeof IngresarRoute
  '/mayorista': typeof MayoristaRoute
  '/panel': typeof PanelRoute
  '/seguimiento': typeof SeguimientoRoute
  '/tienda': typeof TiendaRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/producto/$id': typeof ProductoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/caja': typeof CajaRoute
  '/carrito': typeof CarritoRoute
  '/ingresar': typeof IngresarRoute
  '/mayorista': typeof MayoristaRoute
  '/panel': typeof PanelRoute
  '/seguimiento': typeof SeguimientoRoute
  '/tienda': typeof TiendaRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/producto/$id': typeof ProductoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/caja': typeof CajaRoute
  '/carrito': typeof CarritoRoute
  '/ingresar': typeof IngresarRoute
  '/mayorista': typeof MayoristaRoute
  '/panel': typeof PanelRoute
  '/seguimiento': typeof SeguimientoRoute
  '/tienda': typeof TiendaRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/producto/$id': typeof ProductoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/caja'
    | '/carrito'
    | '/ingresar'
    | '/mayorista'
    | '/panel'
    | '/seguimiento'
    | '/tienda'
    | '/pedido/$id'
    | '/producto/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/caja'
    | '/carrito'
    | '/ingresar'
    | '/mayorista'
    | '/panel'
    | '/seguimiento'
    | '/tienda'
    | '/pedido/$id'
    | '/producto/$id'
  id:
    | '__root__'
    | '/'
    | '/caja'
    | '/carrito'
    | '/ingresar'
    | '/mayorista'
    | '/panel'
    | '/seguimiento'
    | '/tienda'
    | '/pedido/$id'
    | '/producto/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CajaRoute: typeof CajaRoute
  CarritoRoute: typeof CarritoRoute
  IngresarRoute: typeof IngresarRoute
  MayoristaRoute: typeof MayoristaRoute
  PanelRoute: typeof PanelRoute
  SeguimientoRoute: typeof SeguimientoRoute
  TiendaRoute: typeof TiendaRoute
  PedidoIdRoute: typeof PedidoIdRoute
  ProductoIdRoute: typeof ProductoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tienda': {
      id: '/tienda'
      path: '/tienda'
      fullPath: '/tienda'
      preLoaderRoute: typeof TiendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seguimiento': {
      id: '/seguimiento'
      path: '/seguimiento'
      fullPath: '/seguimiento'
      preLoaderRoute: typeof SeguimientoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mayorista': {
      id: '/mayorista'
      path: '/mayorista'
      fullPath: '/mayorista'
      preLoaderRoute: typeof MayoristaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingresar': {
      id: '/ingresar'
      path: '/ingresar'
      fullPath: '/ingresar'
      preLoaderRoute: typeof IngresarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrito': {
      id: '/carrito'
      path: '/carrito'
      fullPath: '/carrito'
      preLoaderRoute: typeof CarritoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caja': {
      id: '/caja'
      path: '/caja'
      fullPath: '/caja'
      preLoaderRoute: typeof CajaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producto/$id': {
      id: '/producto/$id'
      path: '/producto/$id'
      fullPath: '/producto/$id'
      preLoaderRoute: typeof ProductoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$id': {
      id: '/pedido/$id'
      path: '/pedido/$id'
      fullPath: '/pedido/$id'
      preLoaderRoute: typeof PedidoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CajaRoute: CajaRoute,
  CarritoRoute: CarritoRoute,
  IngresarRoute: IngresarRoute,
  MayoristaRoute: MayoristaRoute,
  PanelRoute: PanelRoute,
  SeguimientoRoute: SeguimientoRoute,
  TiendaRoute: TiendaRoute,
  PedidoIdRoute: PedidoIdRoute,
  ProductoIdRoute: ProductoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
